#!/usr/bin/perl
#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::Build::CreateLinks qw(:all);

#
# nethserver-rh-php73-php-fpm event
#

event_actions('nethserver-rh-php73-php-fpm-update', qw(
    initialize-default-databases        00
));

event_templates("nethserver-rh-php73-php-fpm-update", qw(
  /etc/opt/rh/rh-php73/php-fpm.d/z_nethserver.conf
));

event_services("nethserver-rh-php73-php-fpm-update", qw(
  rh-php73-php-fpm restart
));
